use("fairfizz-db");

db.products.deleteMany({});

db.products.insertMany([
  {
    _id: ObjectId("66a100000000000000000001"),
    name: "Classic Cola",
    brand: "FairFizz",
    flavor: "Cola",
    flavorColor: "#3a0ca3",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: true,
    description: "Bold, refreshing cola with real cane sugar.",
    category: "Soda",
    stock: 150,
  },
  {
    _id: ObjectId("66a100000000000000000002"),
    name: "Sugar-Free Cola",
    brand: "FairFizz",
    flavor: "Cola",
    flavorColor: "#3a0ca3",
    size: "355ml",
    price: 20,
    sugar: false,
    caffeine: true,
    description: "All the cola taste, zero sugar.",
    category: "Soda",
    stock: 120,
  },
  {
    _id: ObjectId("66a100000000000000000003"),
    name: "Sparkling Lemonade",
    brand: "Citrus Wave",
    flavor: "Lemon",
    flavorColor: "#facc15",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Zesty lemon fizz made with real lemons.",
    category: "Soda",
    stock: 200,
  },
  {
    _id: ObjectId("66a100000000000000000004"),
    name: "Diet Sparkling Lemonade",
    brand: "Citrus Wave",
    flavor: "Lemon",
    flavorColor: "#facc15",
    size: "355ml",
    price: 20,
    sugar: false,
    caffeine: false,
    description: "Sugar-free lemon bliss with zero compromise.",
    category: "Soda",
    stock: 180,
  },
  {
    _id: ObjectId("66a100000000000000000005"),
    name: "Root Beer Float",
    brand: "FairFizz",
    flavor: "Root Beer",
    flavorColor: "#713f12",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Creamy root beer with a rich, smooth finish.",
    category: "Soda",
    stock: 90,
  },
  {
    _id: ObjectId("66a100000000000000000006"),
    name: "Caffeine-Free Cola",
    brand: "FairFizz",
    flavor: "Cola",
    flavorColor: "#3a0ca3",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Classic cola taste, completely caffeine-free.",
    category: "Soda",
    stock: 75,
  },
  {
    _id: ObjectId("66a100000000000000000007"),
    name: "Ginger Zing",
    brand: "Spice Co.",
    flavor: "Ginger",
    flavorColor: "#ea580c",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Fiery ginger kick with a crisp finish.",
    category: "Soda",
    stock: 60,
  },
  {
    _id: ObjectId("66a100000000000000000008"),
    name: "Sugar-Free Ginger Zing",
    brand: "Spice Co.",
    flavor: "Ginger",
    flavorColor: "#ea580c",
    size: "355ml",
    price: 20,
    sugar: false,
    caffeine: false,
    description: "All the heat, none of the sugar.",
    category: "Soda",
    stock: 55,
  },
  {
    _id: ObjectId("66a100000000000000000009"),
    name: "Blue Raspberry Fizz",
    brand: "FairFizz",
    flavor: "Raspberry",
    flavorColor: "#2563eb",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: true,
    description: "Bold berry flavor with an extra caffeine kick.",
    category: "Soda",
    stock: 140,
  },
  {
    _id: ObjectId("66a10000000000000000000a"),
    name: "Tropical Punch",
    brand: "Island Breeze",
    flavor: "Tropical",
    flavorColor: "#f97316",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "A sunshine blend of mango, pineapple, and passion fruit.",
    category: "Soda",
    stock: 110,
  },
  {
    _id: ObjectId("66a10000000000000000000b"),
    name: "Diet Tropical Punch",
    brand: "Island Breeze",
    flavor: "Tropical",
    flavorColor: "#f97316",
    size: "355ml",
    price: 20,
    sugar: false,
    caffeine: false,
    description: "Island vibes without the sugar crash.",
    category: "Soda",
    stock: 95,
  },
  {
    _id: ObjectId("66a10000000000000000000c"),
    name: "Cherry Bomb",
    brand: "FairFizz",
    flavor: "Cherry",
    flavorColor: "#dc2626",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: true,
    description: "Intense cherry flavor with a caffeine charge.",
    category: "Soda",
    stock: 130,
  },
  {
    _id: ObjectId("66a10000000000000000000d"),
    name: "Grape Fizz",
    brand: "FairFizz",
    flavor: "Grape",
    flavorColor: "#7c3aed",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Sweet grape soda that pops with every sip.",
    category: "Soda",
    stock: 85,
  },
  {
    _id: ObjectId("66a10000000000000000000e"),
    name: "Orange Cream Soda",
    brand: "FairFizz",
    flavor: "Orange",
    flavorColor: "#f97316",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Dreamy vanilla-orange fusion in every bubble.",
    category: "Soda",
    stock: 70,
  },
  {
    _id: ObjectId("66a10000000000000000000f"),
    name: "Large Classic Cola",
    brand: "FairFizz",
    flavor: "Cola",
    flavorColor: "#3a0ca3",
    size: "500ml",
    price: 20,
    sugar: true,
    caffeine: true,
    description: "Bigger bottle, same bold cola taste.",
    category: "Soda",
    stock: 100,
  },
  {
    _id: ObjectId("66a100000000000000000010"),
    name: "Large Sugar-Free Cola",
    brand: "FairFizz",
    flavor: "Cola",
    flavorColor: "#3a0ca3",
    size: "500ml",
    price: 20,
    sugar: false,
    caffeine: true,
    description: "Big bottle, zero sugar, all flavor.",
    category: "Soda",
    stock: 90,
  },
  {
    _id: ObjectId("66a100000000000000000011"),
    name: "Blue Hawaii",
    brand: "FairFizz",
    flavor: "Blue Hawaii",
    flavorColor: "#06b6d4",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "A tropical mocktail blend of pineapple, lime, and blue curacao syrup.",
    category: "Mocktail",
    stock: 80,
  },
  {
    _id: ObjectId("66a100000000000000000012"),
    name: "Strawberry Lemonade",
    brand: "FairFizz",
    flavor: "Strawberry Lemonade",
    flavorColor: "#f43f5e",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Sweet strawberry fused with tangy lemon fizz.",
    category: "Mocktail",
    stock: 110,
  },
  {
    _id: ObjectId("66a100000000000000000013"),
    name: "GRAPE LEMONADE",
    brand: "FairFizz",
    flavor: "GRAPE LEMONADE",
    flavorColor: "#a855f7",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Bold grape meets zesty lemonade in every sparkling sip.",
    category: "Mocktail",
    stock: 95,
  },
  {
    _id: ObjectId("66a100000000000000000014"),
    name: "MOJITO",
    brand: "FairFizz",
    flavor: "MOJITO",
    flavorColor: "#22c55e",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "A refreshing non-alcoholic mojito with mint, lime, and sparkling water.",
    category: "Mocktail",
    stock: 70,
  },
  {
    _id: ObjectId("66a100000000000000000015"),
    name: "Punch",
    brand: "FairFizz",
    flavor: "Punch",
    flavorColor: "#e11d48",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "A vibrant medley of fruit juices with a sparkling kick.",
    category: "Mocktail",
    stock: 100,
  },
  {
    _id: ObjectId("66a100000000000000000019"),
    name: "Watermelon Fizz",
    brand: "FairFizz",
    flavor: "Watermelon",
    flavorColor: "#ff6b6b",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Juicy watermelon that tastes like summer in a can.",
    category: "Soda",
    stock: 100,
  },
  {
    _id: ObjectId("66a10000000000000000001a"),
    name: "Green Apple",
    brand: "FairFizz",
    flavor: "Green Apple",
    flavorColor: "#84cc16",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Crisp, tart green apple with a sharp bite.",
    category: "Soda",
    stock: 95,
  },
  {
    _id: ObjectId("66a10000000000000000001b"),
    name: "Peach Bellini",
    brand: "FairFizz",
    flavor: "Peach",
    flavorColor: "#fb923c",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Ripe peach sweetness with a gentle sparkle.",
    category: "Soda",
    stock: 85,
  },
  {
    _id: ObjectId("66a10000000000000000001c"),
    name: "Pineapple Burst",
    brand: "FairFizz",
    flavor: "Pineapple",
    flavorColor: "#fbbf24",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Tropical pineapple that explodes with flavor.",
    category: "Soda",
    stock: 110,
  },
  {
    _id: ObjectId("66a10000000000000000001d"),
    name: "Coconut Cream",
    brand: "FairFizz",
    flavor: "Coconut",
    flavorColor: "#e2e8f0",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Smooth coconut cream with a light tropical fizz.",
    category: "Soda",
    stock: 75,
  },
  {
    _id: ObjectId("66a10000000000000000001e"),
    name: "Mango Tango",
    brand: "FairFizz",
    flavor: "Mango",
    flavorColor: "#f59e0b",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Sun-ripened mango sweetness in every sip.",
    category: "Soda",
    stock: 105,
  },
  {
    _id: ObjectId("66a10000000000000000001f"),
    name: "Lychee Rose",
    brand: "FairFizz",
    flavor: "Lychee",
    flavorColor: "#f472b6",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Exotic lychee with a hint of rose petals.",
    category: "Soda",
    stock: 80,
  },
  {
    _id: ObjectId("66a100000000000000000020"),
    name: "Cranberry Zing",
    brand: "FairFizz",
    flavor: "Cranberry",
    flavorColor: "#be123c",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Tart cranberry with a bold, crisp finish.",
    category: "Soda",
    stock: 90,
  },
  {
    _id: ObjectId("66a100000000000000000021"),
    name: "Pomegranate Fizz",
    brand: "FairFizz",
    flavor: "Pomegranate",
    flavorColor: "#b91c1c",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Deep, rich pomegranate with a ruby sparkle.",
    category: "Soda",
    stock: 85,
  },
  {
    _id: ObjectId("66a100000000000000000022"),
    name: "Cucumber Lime",
    brand: "FairFizz",
    flavor: "Cucumber",
    flavorColor: "#4ade80",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Cool cucumber and zesty lime — ultra refreshing.",
    category: "Soda",
    stock: 95,
  },
  {
    _id: ObjectId("66a100000000000000000023"),
    name: "Mint Mojito",
    brand: "FairFizz",
    flavor: "Mint",
    flavorColor: "#34d399",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Fresh mint leaves and a hint of lime fizz.",
    category: "Soda",
    stock: 70,
  },
  {
    _id: ObjectId("66a100000000000000000024"),
    name: "Vanilla Cream Soda",
    brand: "FairFizz",
    flavor: "Vanilla",
    flavorColor: "#fde68a",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Silky vanilla with a creamy cloud of bubbles.",
    category: "Soda",
    stock: 80,
  },
  {
    _id: ObjectId("66a100000000000000000025"),
    name: "Toasted Marshmallow",
    brand: "FairFizz",
    flavor: "Marshmallow",
    flavorColor: "#d6d3d1",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Warm toasted marshmallow — a campfire in a can.",
    category: "Soda",
    stock: 60,
  },
  {
    _id: ObjectId("66a100000000000000000026"),
    name: "Bubblegum Pop",
    brand: "FairFizz",
    flavor: "Bubblegum",
    flavorColor: "#f0abfc",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Nostalgic bubblegum sweetness with extra fizz.",
    category: "Soda",
    stock: 120,
  },
  {
    _id: ObjectId("66a100000000000000000027"),
    name: "Cotton Candy",
    brand: "FairFizz",
    flavor: "Cotton Candy",
    flavorColor: "#fbcfe8",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Fluffy pink cotton candy spun into soda form.",
    category: "Soda",
    stock: 125,
  },
  {
    _id: ObjectId("66a100000000000000000028"),
    name: "Honey Lemon",
    brand: "FairFizz",
    flavor: "Honey Lemon",
    flavorColor: "#fef08a",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Golden honey meets tangy lemon in perfect harmony.",
    category: "Soda",
    stock: 90,
  },
  {
    _id: ObjectId("66a100000000000000000029"),
    name: "Elderflower Spritz",
    brand: "FairFizz",
    flavor: "Elderflower",
    flavorColor: "#d8b4fe",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Floral elderflower with a delicate sparkling finish.",
    category: "Soda",
    stock: 65,
  },
  {
    _id: ObjectId("66a10000000000000000002a"),
    name: "Yuzu Citrus",
    brand: "FairFizz",
    flavor: "Yuzu",
    flavorColor: "#fde047",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Aromatic Japanese yuzu with a bright citrus pop.",
    category: "Soda",
    stock: 55,
  },
  {
    _id: ObjectId("66a10000000000000000002b"),
    name: "Guava Bliss",
    brand: "FairFizz",
    flavor: "Guava",
    flavorColor: "#fb7185",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Sweet tropical guava with a lush, juicy fizz.",
    category: "Soda",
    stock: 85,
  },
  {
    _id: ObjectId("66a10000000000000000002c"),
    name: "Kiwi Splash",
    brand: "FairFizz",
    flavor: "Kiwi",
    flavorColor: "#a3e635",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Zippy kiwi with a tangy splash of green goodness.",
    category: "Soda",
    stock: 90,
  },
  {
    _id: ObjectId("66a10000000000000000002d"),
    name: "Blackberry Fizz",
    brand: "FairFizz",
    flavor: "Blackberry",
    flavorColor: "#6b21a8",
    size: "355ml",
    price: 20,
    sugar: true,
    caffeine: false,
    description: "Deep, dark blackberry with a bold berry kick.",
    category: "Soda",
    stock: 80,
  },
  {
    _id: ObjectId("66a100000000000000000016"),
    name: "Choose Your Own 6-Pack",
    brand: "FairFizz",
    flavor: "Mix & Match",
    flavorColor: "#d946ef",
    size: "6 x 355ml",
    price: 89,
    sugar: false,
    caffeine: false,
    description: "Pick any 6 cans from all our flavors. Build your perfect pack.",
    category: "Bundle",
    stock: 999,
  },
  {
    _id: ObjectId("66a100000000000000000017"),
    name: "Choose Your Own 12-Pack",
    brand: "FairFizz",
    flavor: "Mix & Match",
    flavorColor: "#d946ef",
    size: "12 x 355ml",
    price: 169,
    sugar: false,
    caffeine: false,
    description: "Double the fun. Pick any 12 cans from all our flavors.",
    category: "Bundle",
    stock: 999,
  },
  {
    _id: ObjectId("66a100000000000000000018"),
    name: "Choose Your Own 24-Pack",
    brand: "FairFizz",
    flavor: "Mix & Match",
    flavorColor: "#d946ef",
    size: "24 x 355ml",
    price: 329,
    sugar: false,
    caffeine: false,
    description: "The ultimate variety. Pick any 24 cans from all our flavors.",
    category: "Bundle",
    stock: 999,
  },
]);

db.products.find({});
